# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator2UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 588)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(200, 180, 431, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_toplama = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_toplama.setObjectName("btn_toplama")
        self.horizontalLayout.addWidget(self.btn_toplama)
        self.btn_cikarma = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_cikarma.setObjectName("btn_cikarma")
        self.horizontalLayout.addWidget(self.btn_cikarma)
        self.btn_bolme = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_bolme.setObjectName("btn_bolme")
        self.horizontalLayout.addWidget(self.btn_bolme)
        self.btn_carpma = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_carpma.setObjectName("btn_carpma")
        self.horizontalLayout.addWidget(self.btn_carpma)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(200, 60, 431, 92))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(101, 16777215))
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txt_sayi1 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_sayi1.setObjectName("txt_sayi1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_sayi1)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(101, 16777215))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txt_sayi2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_sayi2.setObjectName("txt_sayi2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_sayi2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(240, 310, 351, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lbl_result = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lbl_result.setText("")
        self.lbl_result.setObjectName("lbl_result")
        self.horizontalLayout_2.addWidget(self.lbl_result)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_toplama.setText(_translate("MainWindow", "Toplama"))
        self.btn_cikarma.setText(_translate("MainWindow", "Çıkarma"))
        self.btn_bolme.setText(_translate("MainWindow", "Bölme"))
        self.btn_carpma.setText(_translate("MainWindow", "Çarpma"))
        self.label.setText(_translate("MainWindow", "Number 1:"))
        self.label_2.setText(_translate("MainWindow", "Number 2:"))
        self.label_3.setText(_translate("MainWindow", "Sonuç:"))
